// Include libs
#include "res.h"

// --- INTER-OBJECT VARS ---
extern const str strContainer[][N_LANGUAGE]; // Strings
#define STRINGS(i) strContainer[i][LANG_SET]

// --- STRINGS ---
#define STR_TITLE "FROGGER"
#define STR_FRANCESCO "Francesco Cardia"
#define STR_MATTEO "Matteo Chiesa"
#define STR_GAME STRINGS(0)
#define STR_BEST STRINGS(1)
#define STR_SETTINGS STRINGS(2)
#define STR_CREDITS STRINGS(3)
#define STR_QUIT STRINGS(4)
#define STR_LANGUAGE STRINGS(5)
#define STR_DIFFICULTY STRINGS(6)
#define STR_SKIN STRINGS(32)
#define STR_COLOR_1 STRINGS(18)
#define STR_COLOR_2 STRINGS(19)
#define STR_VOL_MUSIC STRINGS(38)
#define STR_VOL_EFFECTS STRINGS(13)
#define STR_APPLY STRINGS(26)
#define STR_CANCEL STRINGS(7)
#define STR_LANG_EN "English"
#define STR_LANG_IT "Italiano"
#define STR_DIFFICULTY_0 STRINGS(8)
#define STR_DIFFICULTY_1 STRINGS(9)
#define STR_DIFFICULTY_2 STRINGS(10)
#define STR_SKIN_0 STRINGS(11)
#define STR_SKIN_1 STRINGS(12)
#define STR_COL_WHT STRINGS(20)
#define STR_COL_RED STRINGS(21)
#define STR_COL_GRN STRINGS(22)
#define STR_COL_YLW STRINGS(23)
#define STR_COL_BLU STRINGS(24)
#define STR_COL_MGT "Magenta"
#define STR_COL_CYN STRINGS(25)
#define STR_COL_GRY STRINGS(35)
#define STR_COL_RNG STRINGS(36)
#define STR_PROJECT STRINGS(14)
#define STR_PAUSE STRINGS(15)
#define STR_RESUME STRINGS(16)
#define STR_HOME STRINGS(17)
#define STR_OVER "Game over"
#define STR_SCORE STRINGS(27)
#define STR_RETRY STRINGS(28)
#define STR_EXTEND STRINGS(29)
#define STR_MINIMUM STRINGS(30)
#define STR_ACTUAL STRINGS(31)
#define STR_QUIT_WARNING STRINGS(33)
#define STR_YES STRINGS(34)
#define STR_NO "No"
#define STR_BULLETS STRINGS(37)